# Generated by Django 4.2.1 on 2023-05-09 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 14, 13, 59, 872891, tzinfo=datetime.timezone.utc)),
        ),
    ]
