# Generated by Django 4.2.1 on 2023-05-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='link_profile_picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
