# Generated by Django 4.2.1 on 2023-05-10 19:39

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.RemoveField(
            model_name='episode',
            name='link_thumbnail',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='link_podcast_picture',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='tags',
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_thumbnail',
            field=models.FileField(blank=True, upload_to='images/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name='podcast',
            name='podcast_thumbnail',
            field=models.FileField(blank=True, upload_to='images/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='audio',
            field=models.FileField(upload_to='audios/', validators=[core.validators.validate_audio_file]),
        ),
        migrations.AlterField(
            model_name='episode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='episodecomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='episodecommentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.CreateModel(
            name='ActionOnCommentNotification',
            fields=[
                ('notificationmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.notificationmodel')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.episodecomment')),
                ('user_who_notifies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.notificationmodel',),
        ),
        migrations.CreateModel(
            name='NewEpisodeNotification',
            fields=[
                ('notificationmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.notificationmodel')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.episode')),
            ],
            bases=('core.notificationmodel',),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.notificationtype'),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='user_to_notify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
