# Generated by Django 4.2.1 on 2023-05-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='slug',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
    ]
