# Generated by Django 4.2.1 on 2023-05-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_episode_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='length',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
