# Generated by Django 4.2.1 on 2023-05-17 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_episode_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='uploade_date',
            new_name='upload_date',
        ),
    ]
