# Generated by Django 4.2.1 on 2023-05-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_episode_id_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='slug',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
