# Generated by Django 4.2.1 on 2023-06-08 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_podcastfollow_podcastfollow_id_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PodcastFollow',
        ),
    ]
