# Generated by Django 4.2.1 on 2023-06-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_podcast_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
